### ISSUE TITLE
How do you use channeladdperm with node-ts?

### ISSUE THREAD

**Issue by Sir-Will** [nikeee/node-ts#10] opened 2016-01-12 14:18 UTC
hey,

running the code below gives me back `[ReferenceError: permid is not defined]`

How do you define the parameters here and how can you add multiple permid's and values? (Docs splits it with `|`)

```javascript
cl.send("channeladdperm", {
    cid: inheritChannel,
    permid: 141,
    permvalue: 3
})
.then(function(data) {
    console.log(data)
})
.fail(function(err) {
    console.log("Fail. :(");
    console.dir(err);
});
```

**Comment by nikeee** [comment] 2016-01-17 04:38
If you need multiple parameter values, just use an array:
```JavaScript
{
	somevalue: [1, 2, 3, 4]
}
```
node-ts will pass them seperated by `|` accordingly.

Are you using a parameter anywhere else?

**Comment by SirWilli** [comment] 2016-01-17 11:04
Hm, how would that work with 2 parameters? Like `permid=141 permvalue=3 | permid=140 permvalue=5`
> Are you using a parameter anywhere else?

What exactly do you mean?

**Comment by nikeee** [comment] 2016-01-17 15:22
> What exactly do you mean?
If you use parameters for any command elsewhere, just to verify that this is not a general bug.

Just tested the lines you provided with my server - everythin works fine.
I am reimplementing major stuff soon - maybe this will resolve your bug.

**Comment by SirWilli** [comment] 2016-01-17 15:44
Hm, weird that it works for you. Which TS server version are you running?

Also do you have any idea why the timeout, close events get triggered on one server but not on a other one?

**Comment by nikeee** [comment] 2016-01-17 16:12
have you tried using https://github.com/gwTumm/node-teamspeak?

**Comment by SirWilli** [comment] 2016-01-17 16:14
No, I haven't, should I? 
If yes do I need to change anything then the require()?

**Comment by nikeee** [comment] 2016-01-17 16:54
It uses callback instead of promises, see https://github.com/gwTumm/node-teamspeak#example-usage.

**Comment by SirWilli** [comment] 2016-02-02 23:41
Any news for a fix in your fork?

**Comment by nikeee** [comment] 2016-02-05 02:54
Since I was unable to reproduce this bug, can you provide a minimum example where this bug occurs? Also, how's your server configured?

**Comment by SirWilli** [comment] 2016-02-05 05:26
That's the complete order how I run it:
```javascript
 cl.send("channelinfo", {cid: inheritChannel}).then(function(data) {
        channel = data.response[0]

        // get channel permissions
        cl.send("channelpermlist", {cid: inheritChannel}).then(function(data) {

            // create the channel
            cl.send("channelcreate", {
                cpid: pid,
                channel_name: name + ' ' + channelData[0],
            }).then(function(data) {
                // set channel permissions
                    cl.send("channeladdperm", {
                        cid: inheritChannel,
                        permid: 141,
                        permvalue: 3
                    })
                    .then(function(data) {
                        console.log(data)
                    })
                    .fail(function(err) {
                        console.log("Fail. :(");
                        console.dir(err);
                    });
            })
            .fail(function(err) {
                console.log("Fail. :(");
                console.dir(err);
            });

        })
        .fail(function(err) {
            console.log("Fail. :(");
            console.dir(err);
        });

    })
    .fail(function(err) {
        console.log("Fail. createChannel");
        console.dir(err);
    });
```

**Comment by SirWilli** [comment] 2016-02-12 14:07
So?

**Comment by nikeee** [comment] 2016-02-13 10:24
This doesn't look like a minimum error reproduction sample. Also, there is missing some information on the used variables (inheritChannel, name, channelData etc).
Does this work (without all the wrapping callbacks and hardcoded params)?
```JavaScript
cl.send("channeladdperm", {
    cid: 1,
    permid: 141,
    permvalue: 3
}).then(function(data) {
    console.dir(data)
}).fail(function(err) {
    console.log("Fail. :(");
    console.dir(err);
});
```

If you've got a minimum sample, could you port it to node-teamspeak and check wether it has this bug too?
I am also working to port the promises from Q to ES6 promises. You might try this one too, but you have to compile manually. It also requires Node.js >= 4.0.0.
https://github.com/nikeee/node-ts/tree/node-4

**Comment by SirWilli** [comment] 2016-02-17 15:51
Oh, I did misunderstand you then.
The snippet you posted works for me too without the other stuff.

**Comment by SirWilli** [comment] 2016-02-17 16:22
I somehow got it working now. Not sure what I did different before but what I still don't understand how I can set the permissions with one `channeladdperm` instead of sending the command for each permission.

If `somevalue: [1, 2, 3, 4]` == `somevalue=1|somevalue=2|somevalue=3|somevalue=4` how can I have 2 parameters before the split `|` with that?

**Comment by nikeee** [comment] 2016-02-17 17:17
This would be something like:
```JavaScript
cl.send("channeladdperm", {
    cid: 1,
    permid: [141, 592],
    permvalue: [3, 2]
})
```
Resulting in an query like `channeladdperm cid=1 permid=141|permid=592 permvalue=3|permvalue=2`. I know the docs state a different example (like this `channeladdperm cid=1 permid=141 permvalue=3|permid=592 permvalue=2`). But according to their docs, it should be as the library does it.

**Comment by SirWilli** [comment] 2016-02-17 17:22
Just tried that and it throws an error:
```
{ cmd: 'channeladdperm',
  options: [],
  text: 'channeladdperm cid=23133 permid=122|permid=137 permvalue=4|permvalue=1',
  parameters: { cid: 23133, permid: [ 122, 137 ], permvalue: [ 4, 1 ] },
  error: { id: 1539, msg: 'parameter not found' },
  response: null,
  rawResponse: null }
```

**Comment by nikeee** [comment] 2016-02-17 17:28
Okay, then they seem to be inconsistent with their docs (as they have been before).
This could also be relevant for @gwTumm.

**Comment by nikeee** [comment] 2016-04-02 11:17
I think I got it fixed.
However, the project was migrated to use ES2015 promises. Therefore, it cannot be compiled for target <= ES5. It must be compiled for ES2015, but the latest node version does not support optional parameters (which will will be emitted during ES2015 compilation).
If you want to try it out now, you need the latest version of node and start it with the `--harmony_default_parameters` flag (according to [this post](https://github.com/nodejs/node/issues/3070#issuecomment-177447635)). However, this didn't work for me. This feature will be available in node v6.0.0.

**Comment by Sir-Will** [comment] 2016-04-06 14:04
Okay, I will wait for node 6 then. The workaround doesn't seem to cause any issues atm.

**Comment by nikeee** [comment] 2016-05-17 06:57
Since node v6 is now out for a while, can you check whether the big is now fixed?

**Comment by Sir-Will** [comment] 2016-08-23 21:54
Sorry for the late reply.
What's the new way for sending the commands? As I get this with node 6:
`TypeError: cl.send(...).then(...).fail is not a function`

**Comment by nikeee** [comment] 2016-08-24 20:21
Since the project now uses ES2015 promises, there is no `fail` function any more. It should be called `catch` now.

**Comment by Sir-Will** [comment] 2016-08-25 02:41
Alright, thanks.

Somehow the response is empty:

```

**Comment by Sir-Will** [comment] 2016-09-01 02:13
@nikeee any news to this?

**Comment by nikeee** [comment] 2016-09-02 13:02
Pretty short on time right now - still investigating.

**Closed** 2016-09-08 19:51 UTC
Labels: bug

**Comment by nikeee** [comment] 2016-09-08 19:52
I think I got it fixed. Could you confirm this please?

**Comment by Sir-Will** [comment] 2016-09-20 13:07
Thanks, that fixed the empty response.
This: https://github.com/nikeee/node-ts/issues/10#issuecomment-185308531 works now too. :)
